
package View;

import Controle.C_Cidade;
import Controle.C_Estado;
import Controle.C_Paciente;
import Modelo.M_Cidade;
import Modelo.M_Estado;
import Modelo.M_Paciente;
import conexao.CarregaTabelas;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lioni
 */
public class Pasciente extends javax.swing.JFrame {
    private List<M_Estado> dadosEstado = new ArrayList<M_Estado>();
    private List<M_Cidade> dadosCidade = new ArrayList<M_Cidade>();
    private ResultSet tabela;   
    int total = 0;
    int linha = 0;
    
    public void preencheTabela()
    {
        C_Paciente cp = new C_Paciente();
        tabela = cp.dadosTabela(txtNome.getText());
        tabela = cp.dadosTabela(txtCarsus.getText());

        String titulo[] = {"Código", "Cartão SUS", "Nome", "Nascimento", "Naturalidade", "Estado", "Cidade", "Endereco", "Nº", "Bairro", "CEP", "CPF", "RG", "Telefone", "Celular", "Estado Cívil", "Pae", "Mae","Sexo"};
        //tabela = cp.consultaDados();
        
        
        
        CarregaTabelas ct = new CarregaTabelas();
        DefaultTableModel model = ct.PreencheTabela(titulo, tabela);
              
        total = 0;
        tabelaPaciente.setModel(model);
        try {
            tabela.beforeFirst();
            
            while(tabela.next())
            {
                total++;
            }
            
            tabela.first();
        } catch (SQLException ex) {
            Logger.getLogger(Pasciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void CarregaComboEstado()
    {
          C_Estado cest = new C_Estado();
        
        dadosEstado = cest.retornaCombo();
        
        int i = 0;
        
        cmbEstado.removeAllItems();
        while(i<dadosEstado.size())
        {
            cmbEstado.addItem(dadosEstado.get(i).getNomeestado());
            i++;
        }
    }
    public void CarregaComboCidade()
    {
          C_Cidade cc = new C_Cidade();
        
        dadosCidade = cc.retornaCombo(nomeestado);
        
        int i = 0;
        
        cmbCidade.removeAllItems();
        while(i<dadosCidade.size())
        {
            cmbCidade.addItem(dadosCidade.get(i).getNomecidade());
            i++;
        }
    }
    
    
    String sexo= "";
    private void radioSexo(){
    
        if (radioMasc.isSelected()) {
            
            sexo = "MASCULINO";
            
                    
        }
        else if(radioFem.isSelected()) {
            sexo = "FEMININO";
            
        }

    }
    String civil = "";
     private void radioCivil(){
    
        if (radioSolteiro.isSelected()) {
            civil = "SOLTEIRO";
        }
        else if (radioCasado.isSelected()) {
            civil = "CASADO";
        }
        else if (radioAmaziado.isSelected()) {
            civil = "AMAZIADO";
        }
        else if (radioDisquitado.isSelected()) {
            civil = "DISQUITADO";
        }
        else if (radioViuvo.isSelected()) {
            civil = "VIUVO";
        }

    }
     FileInputStream arquivofoto = null;
     private void carregaFoto(){
            
        try {
            arquivofoto = new FileInputStream(txtnomeimagem.getText());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Pasciente.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    public Pasciente() {
        initComponents();
        preencheTabela();
        CarregaComboCidade();
        CarregaComboEstado();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupSexo = new javax.swing.ButtonGroup();
        GroupCivil = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        bntNovo = new javax.swing.JButton();
        bntInserir = new javax.swing.JButton();
        bntAlterar = new javax.swing.JButton();
        bntEscluir = new javax.swing.JButton();
        imagemFoto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPaciente = new javax.swing.JTable();
        txtCarsus = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox();
        addEstado = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cmbCidade = new javax.swing.JComboBox();
        addCep1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        txtNascimento = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        txtNaturalidade = new javax.swing.JTextField();
        txtCep = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        radioFem = new javax.swing.JRadioButton();
        radioMasc = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        txtRg = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPai = new javax.swing.JTextField();
        txtMae = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        radioDisquitado = new javax.swing.JRadioButton();
        radioSolteiro = new javax.swing.JRadioButton();
        radioAmaziado = new javax.swing.JRadioButton();
        radioCasado = new javax.swing.JRadioButton();
        radioViuvo = new javax.swing.JRadioButton();
        txtnomeimagem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        bntNovo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntNovo.setText("Novo");
        bntNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(bntNovo);

        bntInserir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntInserir.setText("Inserir");
        bntInserir.setMargin(new java.awt.Insets(5, 14, 5, 14));
        bntInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntInserirActionPerformed(evt);
            }
        });
        jToolBar1.add(bntInserir);

        bntAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntAlterar.setText("Alterar");
        bntAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAlterarActionPerformed(evt);
            }
        });
        jToolBar1.add(bntAlterar);

        bntEscluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntEscluir.setText("Excluir");
        bntEscluir.setAutoscrolls(true);
        bntEscluir.setMargin(new java.awt.Insets(5, 14, 5, 14));
        bntEscluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEscluirActionPerformed(evt);
            }
        });
        jToolBar1.add(bntEscluir);

        imagemFoto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        imagemFoto.setForeground(new java.awt.Color(204, 204, 204));
        imagemFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagemFoto.setText("SEM FOTO");
        imagemFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        imagemFoto.setName(""); // NOI18N
        imagemFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagemFotoMouseClicked(evt);
            }
        });

        tabelaPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPacienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaPaciente);

        txtCarsus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCarsus.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtCarsusCaretUpdate(evt);
            }
        });
        txtCarsus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarsusActionPerformed(evt);
            }
        });
        txtCarsus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCarsusFocusLost(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Endereço:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Endereço:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nº:");

        txtNumero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Bairro:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Data Nascimento");

        txtRua.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuaActionPerformed(evt);
            }
        });
        txtRua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRuaKeyReleased(evt);
            }
        });

        txtBairro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });
        txtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBairroKeyReleased(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Região"));
        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(230, 445));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Estado:");

        cmbEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });

        addEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/add.jpg"))); // NOI18N
        addEstado.setBorder(null);
        addEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEstadoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Cidade:");

        cmbCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbCidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCidadeActionPerformed(evt);
            }
        });

        addCep1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/add.jpg"))); // NOI18N
        addCep1.setBorder(null);
        addCep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCep1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cmbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addCep1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCep1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Telefônes"));
        jPanel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Telefone:");

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTelefone.setToolTipText("");
        txtTelefone.setDoubleBuffered(true);
        txtTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Celular:");

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelular.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCelular.setToolTipText("");
        txtCelular.setDoubleBuffered(true);
        txtCelular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("CEP:");

        try {
            txtNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNascimento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNascimento.setToolTipText("");
        txtNascimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNascimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNascimentoKeyPressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Naturalidade:");

        txtNaturalidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNaturalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNaturalidadeActionPerformed(evt);
            }
        });
        txtNaturalidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNaturalidadeKeyReleased(evt);
            }
        });

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Sexo"));
        jPanel2.setPreferredSize(new java.awt.Dimension(223, 445));

        GroupSexo.add(radioFem);
        radioFem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioFem.setText("Feminino");

        GroupSexo.add(radioMasc);
        radioMasc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioMasc.setText("Masculino");
        radioMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMascActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioMasc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(radioFem)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioMasc)
                    .addComponent(radioFem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(txtNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
                        .addGap(77, 77, 77)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(29, 29, 29)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Nº Cartão SUS:");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });

        try {
            txtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRg.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Filiação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Nome do Pai:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Nome do Mãe:");

        txtPai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtMae.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPai, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMae, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(txtPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("RG:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("CPF:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nome:");

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNome.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNomeCaretUpdate(evt);
            }
        });
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Estado Civil"));
        jPanel6.setPreferredSize(new java.awt.Dimension(223, 95));

        GroupCivil.add(radioDisquitado);
        radioDisquitado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioDisquitado.setText("Disquitado(a)");

        GroupCivil.add(radioSolteiro);
        radioSolteiro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioSolteiro.setText("Solteiro(a)");
        radioSolteiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSolteiroActionPerformed(evt);
            }
        });

        GroupCivil.add(radioAmaziado);
        radioAmaziado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioAmaziado.setText("Amaziado(a)");
        radioAmaziado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAmaziadoActionPerformed(evt);
            }
        });

        GroupCivil.add(radioCasado);
        radioCasado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioCasado.setText("Casado(a)");
        radioCasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCasadoActionPerformed(evt);
            }
        });

        GroupCivil.add(radioViuvo);
        radioViuvo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioViuvo.setText("Viuvo(a)");
        radioViuvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioViuvoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(radioSolteiro)
                .addGap(75, 75, 75)
                .addComponent(radioAmaziado)
                .addGap(75, 75, 75)
                .addComponent(radioCasado)
                .addGap(75, 75, 75)
                .addComponent(radioDisquitado)
                .addGap(75, 75, 75)
                .addComponent(radioViuvo)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioSolteiro)
                    .addComponent(radioDisquitado)
                    .addComponent(radioAmaziado)
                    .addComponent(radioCasado)
                    .addComponent(radioViuvo))
                .addGap(14, 14, 14))
        );

        txtnomeimagem.setBorder(null);
        txtnomeimagem.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtnomeimagem.setEnabled(false);
        txtnomeimagem.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imagemFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomeimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCarsus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addContainerGap(280, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagemFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnomeimagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 85, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel11))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCarsus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(641, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNovoActionPerformed
        this.dispose();
        new Pasciente().setVisible(true);
    }//GEN-LAST:event_bntNovoActionPerformed

    private void bntInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntInserirActionPerformed
        M_Paciente mp = new M_Paciente();
        
        radioSexo();
        radioCivil();
        
        
        
        
        
       
        if("".equals(txtNome.getText()))
            {JOptionPane.showMessageDialog(null, "Campo Nome é Obrigatorios!!!");}
        else if("".equals(txtRua.getText()))
            {JOptionPane.showMessageDialog(null, "Campo Endereço é Obrigatorios!!!");}
        else if("".equals(txtNumero.getText()))
            {JOptionPane.showMessageDialog(null, "Campo Número é Obrigatorios!!!");}
        else{
                
                mp.setNome(txtNome.getText());
                mp.setCarsus(Integer.parseInt(txtCarsus.getText()));
                mp.setCpf(txtCpf.getText());
                mp.setRg(txtRg.getText());
                mp.setEndereco(txtRua.getText());
                mp.setNumero(txtNumero.getText());
                mp.setBairro(txtBairro.getText());
                mp.setCep(txtCep.getText());
                mp.setNascimento(txtNascimento.getText());
                mp.setNaturalidade(txtNaturalidade.getText());
                mp.setTelefone(txtTelefone.getText());
                mp.setCelular(txtCelular.getText());
                mp.setId_estado(dadosEstado.get(linha).getId_estado());
                mp.setId_cidade(dadosCidade.get(linha).getId_cidade());
                mp.setSexo(sexo);        
                mp.setNomepai(txtPai.getText());
                mp.setNomemae(txtMae.getText());
                mp.setEstado_civil(civil);
                mp.setFoto(arquivofoto);


            C_Paciente cp = new C_Paciente();
            cp.inserirSql((Object)mp);
        }  
        
        preencheTabela();

        tabelaPaciente.setRowSelectionInterval(linha, 0);
    }//GEN-LAST:event_bntInserirActionPerformed

    private void bntAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAlterarActionPerformed
        M_Paciente mp = new M_Paciente();
        carregaFoto();
        radioSexo();
        radioCivil();
                
        mp.setId_paciente(id_paciente);
        mp.setNome(txtNome.getText());
        mp.setCarsus(Integer.parseInt(txtCarsus.getText()));
        mp.setCpf(txtCpf.getText());
        mp.setRg(txtRg.getText());
        mp.setEndereco(txtRua.getText());
        mp.setNumero(txtNumero.getText());
        mp.setBairro(txtBairro.getText());
        mp.setCep(txtCep.getText());
        mp.setNascimento(txtNascimento.getText());
        mp.setNaturalidade(txtNaturalidade.getText());
        mp.setTelefone(txtTelefone.getText());
        mp.setCelular(txtCelular.getText());
        mp.setId_estado(dadosEstado.get(linha).getId_estado());
        mp.setId_cidade(dadosCidade.get(linha).getId_cidade());
        mp.setSexo(sexo);
        mp.setNomepai(txtPai.getText());
        mp.setNomemae(txtMae.getText());
        mp.setEstado_civil(civil);
        //mp.setFoto(arquivofoto);

        C_Paciente cp = new C_Paciente();
        cp.alterarSql((Object)mp);
        preencheTabela();

        tabelaPaciente.setRowSelectionInterval(linha, 0);
    }//GEN-LAST:event_bntAlterarActionPerformed

    private void bntEscluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEscluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null,"Confirma a exclusão", "Exclusão",JOptionPane.YES_NO_OPTION);
        if(resposta == 0){
            M_Paciente mp = new M_Paciente();       
            mp.setId_paciente(id_paciente);
            C_Paciente cp = new C_Paciente();
            cp.excluiSql((Object)mp);
        }            
        
        

        preencheTabela();

        tabelaPaciente.setRowSelectionInterval(linha, 0);
    }//GEN-LAST:event_bntEscluirActionPerformed
private String nome,nascimento,carsus,numero,cpf,rg,telefone,naturalidade,end,estadocivil,cep,pai,mae,celular,bairro,sexo2,estado,cidade;
private int id_paciente;
private FileInputStream foto2;
    private void tabelaPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPacienteMouseClicked
//Código", "Cartão SUS", "Nome", "Nascimento", "Naturalidade", "Estado", "Cidade", "Endereco", "Nº", "Bairro", 
//"CEP", "CPF", "RG", "Telefone", "Celular", "Estado Cívil", "Pae", "Mae","Sexo"
        
        int linha = tabelaPaciente.getSelectedRow();
        id_paciente = Integer.parseInt(tabelaPaciente.getValueAt(linha, 0).toString());
        carsus = tabelaPaciente.getValueAt(linha, 1).toString();
        nome = tabelaPaciente.getValueAt(linha, 2).toString();
        nascimento = tabelaPaciente.getValueAt(linha, 3).toString();
        naturalidade = tabelaPaciente.getValueAt(linha, 4).toString();
        estado = tabelaPaciente.getValueAt(linha, 5).toString();
        cidade = tabelaPaciente.getValueAt(linha, 6).toString();
        end = tabelaPaciente.getValueAt(linha, 7).toString();
        numero = tabelaPaciente.getValueAt(linha, 8).toString();
        bairro = tabelaPaciente.getValueAt(linha, 9).toString();
        cep = tabelaPaciente.getValueAt(linha, 10).toString();
        cpf = tabelaPaciente.getValueAt(linha, 11).toString();
        rg = tabelaPaciente.getValueAt(linha, 12).toString();
        telefone = tabelaPaciente.getValueAt(linha, 13).toString();
        celular = tabelaPaciente.getValueAt(linha, 14).toString();
        estadocivil = tabelaPaciente.getValueAt(linha, 15).toString();
        pai = tabelaPaciente.getValueAt(linha, 16).toString();
        mae = tabelaPaciente.getValueAt(linha, 17).toString();
        sexo2 = tabelaPaciente.getValueAt(linha, 18).toString();
        //foto2 = (FileInputStream) tabelaPaciente.getValueAt(linha, 19);

        //foto2 = (FileInputStream) tabelaPaciente.getValueAt(linha, 19);
        
        
        txtNome.setText(nome);
        cmbEstado.setSelectedItem(estado);
        cmbCidade.setSelectedItem(cidade);
        txtCarsus.setText(carsus);
        txtNascimento.setText(nascimento);
        txtNaturalidade.setText(naturalidade);
        txtRua.setText(end);
        txtCelular.setText(celular);
        txtBairro.setText(bairro);
        txtCep.setText(cep);
        txtCpf.setText(cpf);
        txtRg.setText(rg);
        txtNumero.setText(numero);
        txtPai.setText(pai);
        txtMae.setText(mae);
        //imagemFoto.setIcon((Icon) foto2);
        
        if("MASCULINO".equals(sexo2)){
            radioMasc.setSelected(true);
        }
        else if("FEMININO".equals(sexo2)){
            radioFem.setSelected(true);                    
        }
        if ("SOLTEIRO".equals(estadocivil)) {radioSolteiro.setSelected(true);}
        else if ("CASADO".equals(estadocivil)) {radioCasado.setSelected(true);}
        else if ("AMAZIADO".equals(estadocivil)) {radioAmaziado.setSelected(true);}
        else if ("DISQUITADO".equals(estadocivil)) {radioDisquitado.setSelected(true);}
        else if ("VIUVO".equals(estadocivil)) {radioViuvo.setSelected(true);}
    }//GEN-LAST:event_tabelaPacienteMouseClicked

    private void txtCarsusFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCarsusFocusLost
        // PESQUISAR NÚMERO CARTAO SUS
    }//GEN-LAST:event_txtCarsusFocusLost

    private void txtRuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRuaKeyReleased
        String temp = txtRua.getText();
        txtRua.setText(temp.toUpperCase());
    }//GEN-LAST:event_txtRuaKeyReleased

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void txtBairroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroKeyReleased
        String temp = txtBairro.getText();
        txtBairro.setText(temp.toUpperCase());
    }//GEN-LAST:event_txtBairroKeyReleased
    private int id_estado;
    private String nomeestado;
    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        if(cmbEstado.getSelectedIndex()>=0){
            int linha = cmbEstado.getSelectedIndex();
            id_estado = dadosEstado.get(linha).getId_estado();
            nomeestado = dadosEstado.get(linha).getNomeestado();

            CarregaComboCidade();

        }
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void addEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEstadoActionPerformed
        Estado es = new Estado();
        es.setVisible(true);
    }//GEN-LAST:event_addEstadoActionPerformed
private int id_cidade;
    private void cmbCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCidadeActionPerformed
        if(cmbCidade.getSelectedIndex()>=0){
            int linha = cmbCidade.getSelectedIndex();
            id_cidade = dadosCidade.get(linha).getId_estado();
        }

    }//GEN-LAST:event_cmbCidadeActionPerformed

    private void addCep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCep1ActionPerformed
        Cidade ci = new Cidade();
        ci.setVisible(true);
    }//GEN-LAST:event_addCep1ActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void txtNaturalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNaturalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNaturalidadeActionPerformed

    private void txtNaturalidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNaturalidadeKeyReleased
        String temp = txtNaturalidade.getText();
        txtNaturalidade.setText(temp.toUpperCase());
    }//GEN-LAST:event_txtNaturalidadeKeyReleased

    private void radioMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMascActionPerformed

    }//GEN-LAST:event_radioMascActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased
        String temp = txtNome.getText();
        txtNome.setText(temp.toUpperCase());
    }//GEN-LAST:event_txtNomeKeyReleased

    private void radioSolteiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSolteiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioSolteiroActionPerformed

    private void radioAmaziadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAmaziadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioAmaziadoActionPerformed

    private void radioCasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCasadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCasadoActionPerformed

    private void radioViuvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioViuvoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioViuvoActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
        preencheTabela();
    }//GEN-LAST:event_txtNomeActionPerformed

    private void imagemFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagemFotoMouseClicked
        // TODO add your handling code here:
        JFileChooser arquivo = new JFileChooser();
        int janela = arquivo.showOpenDialog(null);
        if(janela == JFileChooser.APPROVE_OPTION){
            File file = arquivo.getSelectedFile();
            txtnomeimagem.setText(String.valueOf(file));          
            Image foto = getToolkit().getImage(txtnomeimagem.getText());
            foto = foto.getScaledInstance(150, 150, Image.SCALE_DEFAULT);
            imagemFoto.setIcon(new ImageIcon(foto));
        }
        
        
    }//GEN-LAST:event_imagemFotoMouseClicked

    private void txtRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuaActionPerformed
private String carsus4;
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        preencheTabela();
        carsus4 = tabelaPaciente.getValueAt(linha, 1).toString();
    
    }//GEN-LAST:event_formWindowActivated

    private void txtCarsusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarsusActionPerformed
        // TODO add your handling code here:
        preencheTabela();
    }//GEN-LAST:event_txtCarsusActionPerformed

    private void txtNomeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNomeCaretUpdate
        // TODO add your handling code here:
        preencheTabela();
    }//GEN-LAST:event_txtNomeCaretUpdate

    private void txtCarsusCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtCarsusCaretUpdate
        // TODO add your handling code here:
        preencheTabela();
    }//GEN-LAST:event_txtCarsusCaretUpdate

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        preencheTabela();
        carsus4 = tabelaPaciente.getValueAt(linha, 1).toString();
        JOptionPane.showMessageDialog(null, carsus4);
       
    }//GEN-LAST:event_formWindowOpened

    private void txtNascimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNascimentoKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNascimentoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pasciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pasciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pasciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pasciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pasciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GroupCivil;
    private javax.swing.ButtonGroup GroupSexo;
    private javax.swing.JButton addCep1;
    private javax.swing.JButton addEstado;
    private javax.swing.JButton bntAlterar;
    private javax.swing.JButton bntEscluir;
    private javax.swing.JButton bntInserir;
    private javax.swing.JButton bntNovo;
    private javax.swing.JComboBox cmbCidade;
    private javax.swing.JComboBox cmbEstado;
    private javax.swing.JLabel imagemFoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JRadioButton radioAmaziado;
    private javax.swing.JRadioButton radioCasado;
    private javax.swing.JRadioButton radioDisquitado;
    private javax.swing.JRadioButton radioFem;
    private javax.swing.JRadioButton radioMasc;
    private javax.swing.JRadioButton radioSolteiro;
    private javax.swing.JRadioButton radioViuvo;
    private javax.swing.JTable tabelaPaciente;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCarsus;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtMae;
    private javax.swing.JFormattedTextField txtNascimento;
    private javax.swing.JTextField txtNaturalidade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPai;
    private javax.swing.JFormattedTextField txtRg;
    private javax.swing.JTextField txtRua;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JTextField txtnomeimagem;
    // End of variables declaration//GEN-END:variables
}
