
package View;

import Controle.C_Combustivel;
import Controle.C_MarcaVeiculo;
import Controle.C_Veiculo;
import Controle.PlacaExistenteException;
import Modelo.M_Combustivel;
import Modelo.M_MarcaVeiculo;
import Modelo.M_Veiculo;
import conexao.CarregaTabelas;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Veiculo extends javax.swing.JFrame {
private List<M_MarcaVeiculo> dadosMarcaVeiculo = new ArrayList<M_MarcaVeiculo>();
private List<M_Combustivel> dadosCombustivel = new ArrayList<M_Combustivel>();
private ResultSet tabela;   
int total = 0;
int linha = 0;

public void preencheTabela()
    {
        C_Veiculo cv = new C_Veiculo();
        tabela = cv.dadosTabela(txtPesquisa.getText());
        
                        //id_veiculo, placa, anofabricacao, anomodelo, chassi, renavam, qtdpassageiros,  patrimonio,    marca,    modelo,    cor,   c.tipo
        String titulo[] = {"Código","Placa","Ano Fab.","Ano Mod.", "Chassi", "Renavam", "Passageiros", "Patrimônio", "Fabricante", "Modelo", "Cor", "Combustível"};
        //tabela = cv.consultaDados();
        
        
        
        CarregaTabelas ct = new CarregaTabelas();
        DefaultTableModel model = ct.PreencheTabela(titulo, tabela);
              
        total = 0;
        tabelaVeiculo.setModel(model);
        try {
            tabela.beforeFirst();
            
            while(tabela.next())
            {
                total++;
            }
            
            tabela.first();
        } catch (SQLException ex) {
            Logger.getLogger(Veiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void CarregaComboMarcaVeiculo()
    {
          C_MarcaVeiculo ce = new C_MarcaVeiculo();
        
        dadosMarcaVeiculo = ce.retornaCombo();
        
        int i = 0;
        
        cmbMarca.removeAllItems();
        while(i<dadosMarcaVeiculo.size())
        {
            cmbMarca.addItem(dadosMarcaVeiculo.get(i).getMarca());
            i++;
        }
    }
    public void CarregaComboCombustivel()
    {
          C_Combustivel ce = new C_Combustivel();
        
        dadosCombustivel = ce.retornaCombo();
        
        int i = 0;
        
        cmbCombustivel.removeAllItems();
        while(i<dadosCombustivel.size())
        {
            cmbCombustivel.addItem(dadosCombustivel.get(i).getTipo());
            i++;
        }
    }

    public Veiculo() {
        initComponents();
        preencheTabela();
        CarregaComboMarcaVeiculo();
        CarregaComboCombustivel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        txtVeiculo = new javax.swing.JTextField();
        cmbMarca = new javax.swing.JComboBox();
        addMarca = new javax.swing.JButton();
        txtPassageiro = new javax.swing.JTextField();
        txtCor = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JFormattedTextField();
        txtPatrimonio = new javax.swing.JTextField();
        txtPesquisa = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaVeiculo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        bntRelatorio = new javax.swing.JButton();
        bntAlterar = new javax.swing.JButton();
        bntEscluir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtAnoModelo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtChassi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtRenavam = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cmbCombustivel = new javax.swing.JComboBox();
        bntInserir = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Veículos");
        setMinimumSize(new java.awt.Dimension(950, 340));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        txtVeiculo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtVeiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVeiculoKeyReleased(evt);
            }
        });

        cmbMarca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbMarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMarcaActionPerformed(evt);
            }
        });

        addMarca.setText("+");
        addMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMarcaActionPerformed(evt);
            }
        });

        txtPassageiro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPassageiro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPassageiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassageiroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassageiroKeyTyped(evt);
            }
        });

        txtCor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorKeyReleased(evt);
            }
        });

        txtAno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoActionPerformed(evt);
            }
        });
        txtAno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAnoKeyReleased(evt);
            }
        });

        try {
            txtPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("???-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPlaca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });
        txtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPlacaKeyReleased(evt);
            }
        });

        txtPatrimonio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPatrimonio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPatrimonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatrimonioActionPerformed(evt);
            }
        });
        txtPatrimonio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPatrimonioKeyReleased(evt);
            }
        });

        txtPesquisa.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPesquisaCaretUpdate(evt);
            }
        });
        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        tabelaVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVeiculoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaVeiculo);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Modelo:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Pesquisa: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Marca: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Ano Fab.: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Qtd Passageiros:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Placa:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Cor:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Patrimônio:");

        jToolBar1.setRollover(true);

        bntRelatorio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntRelatorio.setText("Novo");
        bntRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRelatorioActionPerformed(evt);
            }
        });
        jToolBar1.add(bntRelatorio);

        bntAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntAlterar.setText("Alterar");
        bntAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAlterarActionPerformed(evt);
            }
        });
        jToolBar1.add(bntAlterar);

        bntEscluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntEscluir.setText("Excluir");
        bntEscluir.setAutoscrolls(true);
        bntEscluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEscluirActionPerformed(evt);
            }
        });
        jToolBar1.add(bntEscluir);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Ano Mod.: ");

        txtAnoModelo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAnoModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoModeloActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Chassi:");

        txtChassi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtChassi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChassiActionPerformed(evt);
            }
        });
        txtChassi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChassiKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Renavam:");

        txtRenavam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRenavam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRenavamActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Combustível: ");

        cmbCombustivel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbCombustivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCombustivelActionPerformed(evt);
            }
        });

        bntInserir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntInserir.setText("Inserir");
        bntInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntInserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bntInserir)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(txtAnoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(txtChassi, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(40, 40, 40)
                                                .addComponent(jLabel5))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtPassageiro)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addMarca)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(cmbCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtAnoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addMarca)
                            .addComponent(cmbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntInserir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(834, 468));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bntInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntInserirActionPerformed
        M_Veiculo mv = new M_Veiculo();
        
        try {
            //...
        }
        catch (PlacaExistenteException) {
            
        }
        
        
       if("".equals(txtPlaca.getText()))
            {JOptionPane.showMessageDialog(null, "Campo Nome é Obrigatorios!!!");}
        else if("".equals(txtPassageiro.getText()))
            {JOptionPane.showMessageDialog(null, "Campo Endereço é Obrigatorios!!!");}
        else if("".equals(txtAno.getText()))
            {JOptionPane.showMessageDialog(null, "Campo Número é Obrigatorios!!!");}
        else if("".equals(txtChassi.getText()))
            {JOptionPane.showMessageDialog(null, "Campo Número é Obrigatorios!!!");}
        else if("".equals(txtRenavam.getText()))
            {JOptionPane.showMessageDialog(null, "Campo Número é Obrigatorios!!!");}
        else if("".equals(txtAnoModelo.getText()))
            {JOptionPane.showMessageDialog(null, "Campo Número é Obrigatorios!!!");}
        else{
        
        mv.setModelo(txtVeiculo.getText());
        mv.setId_marca(id_marca);
        mv.setQtdpassageiro(Integer.parseInt(txtPassageiro.getText()));
        mv.setCor(txtCor.getText());
        mv.setAnofabricacao(Integer.parseInt(txtAno.getText()));
        mv.setPlaca(txtPlaca.getText());
        mv.setPatrimonio(txtPatrimonio.getText());
        mv.setId_combustivel(id_combustivel);
        mv.setChassi(txtChassi.getText());
        mv.setRenavam(Integer.parseInt(txtRenavam.getText()));
        mv.setAnomodelo(Integer.parseInt(txtAnoModelo.getText()));
        
        C_Veiculo cv = new C_Veiculo();
        cv.inserirSql((Object)mv);
        }
        preencheTabela();
        
        tabelaVeiculo.setRowSelectionInterval(linha, 0);
    }//GEN-LAST:event_bntInserirActionPerformed

    private void bntAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAlterarActionPerformed
        M_Veiculo mv = new M_Veiculo();
       
        mv.setModelo(txtVeiculo.getText());
        mv.setId_marca(id_marca);
        mv.setQtdpassageiro(Integer.parseInt(txtPassageiro.getText()));
        mv.setCor(txtCor.getText());
        mv.setAnofabricacao(Integer.parseInt(txtAno.getText()));
        mv.setPlaca(txtPlaca.getText());
        mv.setPatrimonio(txtPatrimonio.getText());
        mv.setId_combustivel(id_combustivel);
        mv.setChassi(txtChassi.getText());
        mv.setRenavam(Integer.parseInt(txtRenavam.getText()));
        mv.setId_veiculo(id_veiculo);
        mv.setAnomodelo(Integer.parseInt(txtAnoModelo.getText()));
        
        C_Veiculo cv = new C_Veiculo();
        cv.alterarSql((Object)mv);
        preencheTabela();
        
        tabelaVeiculo.setRowSelectionInterval(linha, 0);
    }//GEN-LAST:event_bntAlterarActionPerformed

    private void bntEscluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEscluirActionPerformed
        M_Veiculo mv = new M_Veiculo();
        int resposta = JOptionPane.showConfirmDialog(null,"Confirma a exclusão", "Exclusão",JOptionPane.YES_NO_OPTION);
        if(resposta == 0){
        mv.setId_veiculo(id_veiculo);
        C_Veiculo cv = new C_Veiculo();
        cv.excluiSql((Object)mv);
        }
        preencheTabela();
              
        tabelaVeiculo.setRowSelectionInterval(linha, 0);
    }//GEN-LAST:event_bntEscluirActionPerformed
    private int id_veiculo;
    private String modelo;
    private String marca;
    private String cor;
    private String anom;
    private String placa;
    private String patrimonio;
    private String combustivel;
    private String anof;
    private String chassi;
    private String renavam;
    private String passag;
    //v.id_veiculo, v.placa, v.anofabricacao, v.anomodelo, v.chassi, v.renavam, v.qtdpassageiros,v.patrimonio, m.marca, v.modelo, v.cor, c.tipo
    private void tabelaVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaVeiculoMouseClicked
        int linha = tabelaVeiculo.getSelectedRow();
        //v.id_veiculo, v.placa, v.anofabricacao, v.anomodelo, v.chassi, 
        //v.renavam, v.qtdpassageiros,v.patrimonio, m.marca, v.modelo, v.cor, c.tipo
        id_veiculo = Integer.parseInt(tabelaVeiculo.getValueAt(linha, 0).toString());
        placa = tabelaVeiculo.getValueAt(linha, 1).toString();
        anof = tabelaVeiculo.getValueAt(linha, 2).toString();
        anom = tabelaVeiculo.getValueAt(linha, 3).toString();
        chassi = tabelaVeiculo.getValueAt(linha, 4).toString();
        renavam = tabelaVeiculo.getValueAt(linha, 5).toString();
        passag = tabelaVeiculo.getValueAt(linha, 6).toString();
        patrimonio = tabelaVeiculo.getValueAt(linha, 7).toString();
        marca = tabelaVeiculo.getValueAt(linha, 8).toString();
        modelo = tabelaVeiculo.getValueAt(linha, 9).toString();
        cor = tabelaVeiculo.getValueAt(linha, 10).toString();
        combustivel = tabelaVeiculo.getValueAt(linha, 11).toString();
        
        txtVeiculo.setText(modelo);
        cmbMarca.setSelectedItem(marca);
        cmbCombustivel.setSelectedItem(combustivel);
        txtPassageiro.setText(passag);
        txtCor.setText(cor);
        txtRenavam.setText(renavam);
        txtChassi.setText(chassi);
        txtAno.setText(anof);
        txtAnoModelo.setText(anom);
        txtPlaca.setText(placa);
        txtPatrimonio.setText(patrimonio);
    }//GEN-LAST:event_tabelaVeiculoMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        CarregaComboMarcaVeiculo();
        CarregaComboCombustivel();
    }//GEN-LAST:event_formWindowActivated

    private void txtVeiculoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVeiculoKeyReleased
        String temp = txtVeiculo.getText();
        txtVeiculo.setText(temp.toUpperCase());
    }//GEN-LAST:event_txtVeiculoKeyReleased

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        String temp = txtPesquisa.getText();
        txtPesquisa.setText(temp.toUpperCase());
    }//GEN-LAST:event_txtPesquisaKeyReleased
        private int id_marca;
    private void cmbMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMarcaActionPerformed
        
        if(cmbMarca.getSelectedIndex()>=0){
            int linha = cmbMarca.getSelectedIndex();
            id_marca = dadosMarcaVeiculo.get(linha).getId_marca();
        }
    }//GEN-LAST:event_cmbMarcaActionPerformed

    private void bntRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRelatorioActionPerformed
        this.dispose();
        new Veiculo().setVisible(true);
    }//GEN-LAST:event_bntRelatorioActionPerformed

    private void txtPassageiroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassageiroKeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
            }



    }//GEN-LAST:event_txtPassageiroKeyTyped

    private void txtPassageiroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassageiroKeyReleased
        //
    }//GEN-LAST:event_txtPassageiroKeyReleased

    private void txtCorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorKeyReleased
        String temp = txtCor.getText();
        txtCor.setText(temp.toUpperCase());
    }//GEN-LAST:event_txtCorKeyReleased

    private void txtPatrimonioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatrimonioKeyReleased
        String temp = txtPatrimonio.getText();
        txtPatrimonio.setText(temp.toUpperCase());
    }//GEN-LAST:event_txtPatrimonioKeyReleased

    private void addMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMarcaActionPerformed
        new MarcaVeiculo().setVisible(true);
    }//GEN-LAST:event_addMarcaActionPerformed

    private void txtPesquisaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPesquisaCaretUpdate
       preencheTabela();
    }//GEN-LAST:event_txtPesquisaCaretUpdate

    private void txtPlacaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyReleased
        String temp = txtPlaca.getText();
        txtPlaca.setText(temp.toUpperCase());
    }//GEN-LAST:event_txtPlacaKeyReleased

    private void txtAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void txtPatrimonioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatrimonioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatrimonioActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void txtAnoModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoModeloActionPerformed

    private void txtChassiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChassiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChassiActionPerformed

    private void txtRenavamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRenavamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRenavamActionPerformed
    private int id_combustivel;
    private void cmbCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCombustivelActionPerformed
        if(cmbCombustivel.getSelectedIndex()>=0){
            int linha = cmbCombustivel.getSelectedIndex();
            id_combustivel = dadosCombustivel.get(linha).getId_combustivel();
        }
    }//GEN-LAST:event_cmbCombustivelActionPerformed

    private void txtAnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoKeyReleased

    private void txtChassiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChassiKeyReleased
        String temp = txtChassi.getText();
        txtChassi.setText(temp.toUpperCase());
    }//GEN-LAST:event_txtChassiKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Veiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Veiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Veiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Veiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Veiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMarca;
    private javax.swing.JButton bntAlterar;
    private javax.swing.JButton bntEscluir;
    private javax.swing.JButton bntInserir;
    private javax.swing.JButton bntRelatorio;
    private javax.swing.JComboBox cmbCombustivel;
    private javax.swing.JComboBox cmbMarca;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tabelaVeiculo;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtAnoModelo;
    private javax.swing.JTextField txtChassi;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtPassageiro;
    private javax.swing.JTextField txtPatrimonio;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JFormattedTextField txtPlaca;
    private javax.swing.JTextField txtRenavam;
    private javax.swing.JTextField txtVeiculo;
    // End of variables declaration//GEN-END:variables
}
